### ISSUE TITLE
Z-indexing issue

### ISSUE THREAD

**Issue by Deependra3010** [AashisThakur/React_project_managment#1]
The Add Task div scrolls over the side navbar. This might be due to the div having opacity-90 [here](https://github.com/AashisThakur/React_project_managment/blob/main/react-kanban/src/pages/Boards/index.tsx#L49) as it may create a new stacking context. Maybe you can remove that class or just add z-index to side navbar :wink:.

![image](https://github.com/AashisThakur/React_project_managment/assets/71078517/87a903d5-44f3-4a80-a3f1-c4c673c87c38)

**Comment by AashisThakur** [comment]
haah resolved the issue i guess that was indeed unnecessary and seems like dnd's also working fine now cheers. ;)
